export const styleSheet ={
    container:{
        width:'100vw',
        //height:'100vh',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        //backgroundColor:'red'
    },
    navBar:{
        width:'100vw',
        height:'10vh',
        backgroundColor: '#92A3E0',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        //justifyContent: 'center',
    },
    bodyContainer:{
        width:'100vw',
        height:'90vh',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
    },
    cardBodyContainer:{
        width:'80vw',
        height:'40vh',
        //border:'1px solid red',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
    },
    card:{
        width:'40vw',
        height:'40vh',
        //border:'1px solid red',
        display: 'flex',
        flexWrap: 'wrap',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    }
}